### ISSUE TITLE
Feature Request : Allow Placement of Buttons Above or Below Course Content

### ISSUE THREAD

**Issue by SamMcCullough** [davosmith/moodle-navbuttons#11]
Hello @davosmith,

We have been enjoying the user of your plugin. Feedback we have been provided would be to allow for positioning of the buttons above or below course content. The thought being, if a browser is not full maximized placing the buttons on top would allow for users to find them without scrolling. 

Thank you,

**Comment by davosmith** [comment]
If you want the navigation above the content, then you'd need to figure out where the top of the content was being output and add the core change there instead - possibly at the bottom of the 'header' function in the same file might work.

This isn't something I can do by changing the code of the plugin.
